interface CountryData {
  countryFlag: string;
  countryName: string;
}

export const countryMap: { [key: string]: CountryData } = {
  AF: { countryFlag: "country-flag-afghanistan", countryName: "Afghanistan" },
  AL: { countryFlag: "country-flag-albania", countryName: "Albania" },
  DZ: { countryFlag: "country-flag-algeria", countryName: "Algeria" },
  AD: { countryFlag: "country-flag-andorra", countryName: "Andorra" },
  AO: { countryFlag: "country-flag-angola", countryName: "Angola" },
  AR: { countryFlag: "country-flag-argentina", countryName: "Argentina" },
  AM: { countryFlag: "country-flag-armenia", countryName: "Armenia" },
  AU: { countryFlag: "country-flag-australia", countryName: "Australia" },
  AT: { countryFlag: "country-flag-austria", countryName: "Austria" },
  AZ: { countryFlag: "country-flag-azerbaijan", countryName: "Azerbaijan" },
  BS: { countryFlag: "country-flag-bahamas", countryName: "Bahamas" },
  BH: { countryFlag: "country-flag-bahrain", countryName: "Bahrain" },
  BD: { countryFlag: "country-flag-bangladesh", countryName: "Bangladesh" },
  BB: { countryFlag: "country-flag-barbados", countryName: "Barbados" },
  BY: { countryFlag: "country-flag-belarus", countryName: "Belarus" },
  BE: { countryFlag: "country-flag-belgium", countryName: "Belgium" },
  BZ: { countryFlag: "country-flag-belize", countryName: "Belize" },
  BJ: { countryFlag: "country-flag-benin", countryName: "Benin" },
  BT: { countryFlag: "country-flag-bhutan", countryName: "Bhutan" },
  BO: { countryFlag: "country-flag-bolivia", countryName: "Bolivia" },
  BA: { countryFlag: "country-flag-bosnia-and-herzegovina", countryName: "Bosnia and Herzegovina" },
  BW: { countryFlag: "country-flag-botswana", countryName: "Botswana" },
  BR: { countryFlag: "country-flag-brazil", countryName: "Brazil" },
  BN: { countryFlag: "country-flag-brunei", countryName: "Brunei" },
  BG: { countryFlag: "country-flag-bulgaria", countryName: "Bulgaria" },
  BF: { countryFlag: "country-flag-burkina-faso", countryName: "Burkina Faso" },
  BI: { countryFlag: "country-flag-burundi", countryName: "Burundi" },
  KH: { countryFlag: "country-flag-cambodia", countryName: "Cambodia" },
  CM: { countryFlag: "country-flag-cameroon", countryName: "Cameroon" },
  CA: { countryFlag: "country-flag-canada", countryName: "Canada" },
  CV: { countryFlag: "country-flag-cape-verde", countryName: "Cape Verde" },
  CF: { countryFlag: "country-flag-central-african-republic", countryName: "Central African Republic" },
  TD: { countryFlag: "country-flag-chad", countryName: "Chad" },
  CL: { countryFlag: "country-flag-chile", countryName: "Chile" },
  CN: { countryFlag: "country-flag-china", countryName: "China" },
  CO: { countryFlag: "country-flag-colombia", countryName: "Colombia" },
  KM: { countryFlag: "country-flag-comoros", countryName: "Comoros" },
  CG: { countryFlag: "country-flag-congo-brazzaville", countryName: "Congo - Brazzaville" },
  CD: { countryFlag: "country-flag-congo-kinshasa", countryName: "Congo - Kinshasa" },
  CR: { countryFlag: "country-flag-costa-rica", countryName: "Costa Rica" },
  CI: { countryFlag: "country-flag-cote-divoire", countryName: "Côte d'Ivoire" },
  HR: { countryFlag: "country-flag-croatia", countryName: "Croatia" },
  CU: { countryFlag: "country-flag-cuba", countryName: "Cuba" },
  CY: { countryFlag: "country-flag-cyprus", countryName: "Cyprus" },
  CZ: { countryFlag: "country-flag-czech-republic", countryName: "Czech Republic" },
  DK: { countryFlag: "country-flag-denmark", countryName: "Denmark" },
  DJ: { countryFlag: "country-flag-djibouti", countryName: "Djibouti" },
  DM: { countryFlag: "country-flag-dominica", countryName: "Dominica" },
  DO: { countryFlag: "country-flag-dominican-republic", countryName: "Dominican Republic" },
  EC: { countryFlag: "country-flag-ecuador", countryName: "Ecuador" },
  EG: { countryFlag: "country-flag-egypt", countryName: "Egypt" },
  SV: { countryFlag: "country-flag-el-salvador", countryName: "El Salvador" },
  GQ: { countryFlag: "country-flag-equatorial-guinea", countryName: "Equatorial Guinea" },
  ER: { countryFlag: "country-flag-eritrea", countryName: "Eritrea" },
  EE: { countryFlag: "country-flag-estonia", countryName: "Estonia" },
  ET: { countryFlag: "country-flag-ethiopia", countryName: "Ethiopia" },
  FJ: { countryFlag: "country-flag-fiji", countryName: "Fiji" },
  FI: { countryFlag: "country-flag-finland", countryName: "Finland" },
  FR: { countryFlag: "country-flag-france", countryName: "France" },
  GA: { countryFlag: "country-flag-gabon", countryName: "Gabon" },
  GM: { countryFlag: "country-flag-gambia", countryName: "Gambia" },
  GE: { countryFlag: "country-flag-georgia", countryName: "Georgia" },
  DE: { countryFlag: "country-flag-germany", countryName: "Germany" },
  GH: { countryFlag: "country-flag-ghana", countryName: "Ghana" },
  GR: { countryFlag: "country-flag-greece", countryName: "Greece" },
  GD: { countryFlag: "country-flag-grenada", countryName: "Grenada" },
  GT: { countryFlag: "country-flag-guatemala", countryName: "Guatemala" },
  GN: { countryFlag: "country-flag-guinea", countryName: "Guinea" },
  GW: { countryFlag: "country-flag-guinea-bissau", countryName: "Guinea-Bissau" },
  GY: { countryFlag: "country-flag-guyana", countryName: "Guyana" },
  HT: { countryFlag: "country-flag-haiti", countryName: "Haiti" },
  HN: { countryFlag: "country-flag-honduras", countryName: "Honduras" },
  HU: { countryFlag: "country-flag-hungary", countryName: "Hungary" },
  IS: { countryFlag: "country-flag-iceland", countryName: "Iceland" },
  IN: { countryFlag: "country-flag-india", countryName: "India" },
  ID: { countryFlag: "country-flag-indonesia", countryName: "Indonesia" },
  IR: { countryFlag: "country-flag-iran", countryName: "Iran" },
  IQ: { countryFlag: "country-flag-iraq", countryName: "Iraq" },
  IE: { countryFlag: "country-flag-ireland", countryName: "Ireland" },
  IL: { countryFlag: "country-flag-israel", countryName: "Israel" },
  IT: { countryFlag: "country-flag-italy", countryName: "Italy" },
  JM: { countryFlag: "country-flag-jamaica", countryName: "Jamaica" },
  JP: { countryFlag: "country-flag-japan", countryName: "Japan" },
  JO: { countryFlag: "country-flag-jordan", countryName: "Jordan" },
  KZ: { countryFlag: "country-flag-kazakhstan", countryName: "Kazakhstan" },
  KE: { countryFlag: "country-flag-kenya", countryName: "Kenya" },
  KI: { countryFlag: "country-flag-kiribati", countryName: "Kiribati" },
  KP: { countryFlag: "country-flag-north-korea", countryName: "North Korea" },
  KR: { countryFlag: "country-flag-south-korea", countryName: "South Korea" },
  KW: { countryFlag: "country-flag-kuwait", countryName: "Kuwait" },
  KG: { countryFlag: "country-flag-kyrgyzstan", countryName: "Kyrgyzstan" },
  LA: { countryFlag: "country-flag-laos", countryName: "Laos" },
  LV: { countryFlag: "country-flag-latvia", countryName: "Latvia" },
  LB: { countryFlag: "country-flag-lebanon", countryName: "Lebanon" },
  LS: { countryFlag: "country-flag-lesotho", countryName: "Lesotho" },
  LR: { countryFlag: "country-flag-liberia", countryName: "Liberia" },
  LY: { countryFlag: "country-flag-libya", countryName: "Libya" },
  LI: { countryFlag: "country-flag-liechtenstein", countryName: "Liechtenstein" },
  LT: { countryFlag: "country-flag-lithuania", countryName: "Lithuania" },
  LU: { countryFlag: "country-flag-luxembourg", countryName: "Luxembourg" },
  MG: { countryFlag: "country-flag-madagascar", countryName: "Madagascar" },
  MW: { countryFlag: "country-flag-malawi", countryName: "Malawi" },
  MY: { countryFlag: "country-flag-malaysia", countryName: "Malaysia" },
  MV: { countryFlag: "country-flag-maldives", countryName: "Maldives" },
  ML: { countryFlag: "country-flag-mali", countryName: "Mali" },
  MT: { countryFlag: "country-flag-malta", countryName: "Malta" },
  MH: { countryFlag: "country-flag-marshall-islands", countryName: "Marshall Islands" },
  MR: { countryFlag: "country-flag-mauritania", countryName: "Mauritania" },
  MU: { countryFlag: "country-flag-mauritius", countryName: "Mauritius" },
  MX: { countryFlag: "country-flag-mexico", countryName: "Mexico" },
  FM: { countryFlag: "country-flag-micronesia", countryName: "Micronesia" },
  MD: { countryFlag: "country-flag-moldova", countryName: "Moldova" },
  MC: { countryFlag: "country-flag-monaco", countryName: "Monaco" },
  MN: { countryFlag: "country-flag-mongolia", countryName: "Mongolia" },
  ME: { countryFlag: "country-flag-montenegro", countryName: "Montenegro" },
  MA: { countryFlag: "country-flag-morocco", countryName: "Morocco" },
  MZ: { countryFlag: "country-flag-mozambique", countryName: "Mozambique" },
  MM: { countryFlag: "country-flag-myanmar", countryName: "Myanmar" },
  NA: { countryFlag: "country-flag-namibia", countryName: "Namibia" },
  NR: { countryFlag: "country-flag-nauru", countryName: "Nauru" },
  NP: { countryFlag: "country-flag-nepal", countryName: "Nepal" },
  NL: { countryFlag: "country-flag-netherlands", countryName: "Netherlands" },
  NZ: { countryFlag: "country-flag-new-zealand", countryName: "New Zealand" },
  NI: { countryFlag: "country-flag-nicaragua", countryName: "Nicaragua" },
  NE: { countryFlag: "country-flag-niger", countryName: "Niger" },
  NG: { countryFlag: "country-flag-nigeria", countryName: "Nigeria" },
  NO: { countryFlag: "country-flag-norway", countryName: "Norway" },
  OM: { countryFlag: "country-flag-oman", countryName: "Oman" },
  PK: { countryFlag: "country-flag-pakistan", countryName: "Pakistan" },
  PW: { countryFlag: "country-flag-palau", countryName: "Palau" },
  PA: { countryFlag: "country-flag-panama", countryName: "Panama" },
  PG: { countryFlag: "country-flag-papua-new-guinea", countryName: "Papua New Guinea" },
  PY: { countryFlag: "country-flag-paraguay", countryName: "Paraguay" },
  PE: { countryFlag: "country-flag-peru", countryName: "Peru" },
  PH: { countryFlag: "country-flag-philippines", countryName: "Philippines" },
  PL: { countryFlag: "country-flag-poland", countryName: "Poland" },
  PT: { countryFlag: "country-flag-portugal", countryName: "Portugal" },
  QA: { countryFlag: "country-flag-qatar", countryName: "Qatar" },
  RO: { countryFlag: "country-flag-romania", countryName: "Romania" },
  RU: { countryFlag: "country-flag-russia", countryName: "Russia" },
  RW: { countryFlag: "country-flag-rwanda", countryName: "Rwanda" },
  KN: { countryFlag: "country-flag-saint-kitts-and-nevis", countryName: "Saint Kitts and Nevis" },
  LC: { countryFlag: "country-flag-saint-lucia", countryName: "Saint Lucia" },
  VC: { countryFlag: "country-flag-saint-vincent-and-the-grenadines", countryName: "Saint Vincent and the Grenadines" },
  WS: { countryFlag: "country-flag-samoa", countryName: "Samoa" },
  SM: { countryFlag: "country-flag-san-marino", countryName: "San Marino" },
  ST: { countryFlag: "country-flag-sao-tome-and-principe", countryName: "São Tomé and Príncipe" },
  SA: { countryFlag: "country-flag-saudi-arabia", countryName: "Saudi Arabia" },
  SN: { countryFlag: "country-flag-senegal", countryName: "Senegal" },
  RS: { countryFlag: "country-flag-serbia", countryName: "Serbia" },
  SC: { countryFlag: "country-flag-seychelles", countryName: "Seychelles" },
  SL: { countryFlag: "country-flag-sierra-leone", countryName: "Sierra Leone" },
  SG: { countryFlag: "country-flag-singapore", countryName: "Singapore" },
  SK: { countryFlag: "country-flag-slovakia", countryName: "Slovakia" },
  SI: { countryFlag: "country-flag-slovenia", countryName: "Slovenia" },
  SB: { countryFlag: "country-flag-solomon-islands", countryName: "Solomon Islands" },
  SO: { countryFlag: "country-flag-somalia", countryName: "Somalia" },
  ZA: { countryFlag: "country-flag-south-africa", countryName: "South Africa" },
  SS: { countryFlag: "country-flag-south-sudan", countryName: "South Sudan" },
  ES: { countryFlag: "country-flag-spain", countryName: "Spain" },
  LK: { countryFlag: "country-flag-sri-lanka", countryName: "Sri Lanka" },
  SD: { countryFlag: "country-flag-sudan", countryName: "Sudan" },
  SR: { countryFlag: "country-flag-suriname", countryName: "Suriname" },
  SZ: { countryFlag: "country-flag-swaziland", countryName: "Eswatini (Swaziland)" },
  SE: { countryFlag: "country-flag-sweden", countryName: "Sweden" },
  CH: { countryFlag: "country-flag-switzerland", countryName: "Switzerland" },
  SY: { countryFlag: "country-flag-syria", countryName: "Syria" },
  TW: { countryFlag: "country-flag-taiwan", countryName: "Taiwan" },
  TJ: { countryFlag: "country-flag-tajikistan", countryName: "Tajikistan" },
  TZ: { countryFlag: "country-flag-tanzania", countryName: "Tanzania" },
  TH: { countryFlag: "country-flag-thailand", countryName: "Thailand" },
  TG: { countryFlag: "country-flag-togo", countryName: "Togo" },
  TO: { countryFlag: "country-flag-tonga", countryName: "Tonga" },
  TT: { countryFlag: "country-flag-trinidad-and-tobago", countryName: "Trinidad and Tobago" },
  TN: { countryFlag: "country-flag-tunisia", countryName: "Tunisia" },
  TR: { countryFlag: "country-flag-turkey", countryName: "Turkey" },
  TM: { countryFlag: "country-flag-turkmenistan", countryName: "Turkmenistan" },
  TV: { countryFlag: "country-flag-tuvalu", countryName: "Tuvalu" },
  UG: { countryFlag: "country-flag-uganda", countryName: "Uganda" },
  UA: { countryFlag: "country-flag-ukraine", countryName: "Ukraine" },
  AE: { countryFlag: "country-flag-united-arab-emirates", countryName: "United Arab Emirates" },
  GB: { countryFlag: "country-flag-united-kingdom", countryName: "United Kingdom" },
  US: { countryFlag: "country-flag-united-states", countryName: "United States" },
  UY: { countryFlag: "country-flag-uruguay", countryName: "Uruguay" },
  UZ: { countryFlag: "country-flag-uzbekistan", countryName: "Uzbekistan" },
  VU: { countryFlag: "country-flag-vanuatu", countryName: "Vanuatu" },
  VA: { countryFlag: "country-flag-vatican-city", countryName: "Vatican City" },
  VE: { countryFlag: "country-flag-venezuela", countryName: "Venezuela" },
  VN: { countryFlag: "country-flag-vietnam", countryName: "Vietnam" },
  YE: { countryFlag: "country-flag-yemen", countryName: "Yemen" },
  ZM: { countryFlag: "country-flag-zambia", countryName: "Zambia" },
  ZW: { countryFlag: "country-flag-zimbabwe", countryName: "Zimbabwe" },
  EU: { countryFlag: "country-flag-europe", countryName: "Europe" },
};

export const getCountryFlag = (countryCode: string | null): CountryData => {
  return countryMap[countryCode || ""] || { countryFlag: "country-flag-unknown", countryName: "Unknown" };
};
